name: leoclinic_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc:
  equatable:

  # Networking
  dio: ^5.11.0

  # Responsive UI
  flutter_screenutil:

  # SVG
  flutter_svg: ^2.3.0

  # Icons
  font_awesome_flutter: ^11.0.0

  # Local Storage
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/font/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/font/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/font/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/font/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/IBMPlexSans-Regular.ttf
          weight: 400

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  field_prefix: